---
- hosts: localhost
  connection: local
  tasks:
    - name: generate private keys for etcd members
      openssl_privatekey:
        path: ./certs/{{ item }}.key
        type: RSA
        size: 4096
        state: present
        force: True
      with_items: "{{ groups['etcd'] }}"

    - name: create request CSR for etcd members
      openssl_csr:
        path: ./certs/{{ item }}.csr
        privatekey_path: ./certs/{{ item }}.key
        common_name: "{{item}}"
        key_usage:
          - digitalSignature
        extended_key_usage:
          - serverAuth
        subject_alt_name:
          - IP:{{ ansible_eth0.ipv4.address }}
          - IP:127.0.0.1
        force: True
      with_items: "{{ groups['etcd'] }}"
